apiVersion: v1
kind: Pod
metadata:
  name: cluster-entitled-build-pod
spec:
  containers:
    - name: cluster-entitled-build
      image: ec2-18-191-238-214.us-east-2.compute.amazonaws.com:5000/ubi8
      command: [ "/bin/sh", "-c", "dnf search kernel-devel --showduplicates" ]
  imagePullPolicy: Always
  restartPolicy: Never
